### ISSUE TITLE
全选按钮颜色异常

### ISSUE THREAD

**Issue by urain39** [uzilla/moeloli.ml#1]
在点击全选按钮以后点击任意空白处会导致按钮组右边边框丢失与中间出现灰色阴影的情况。

**Comment by urain39** [comment]
此问题仅在安卓手机7.x 1080p分辨率复现。

**Comment by urain39** [comment]
貌似莫名其妙的被这两个commit修复了。。

**Comment by urain39** [comment]
初步确定已修复，如复现再重新开启此issues。

**Comment by urain39** [comment]
问题重开，此问题好像只在当没有正在下载的任务时但有已完成的任务，换句话说就是只在所有任务完成时出现。

**Comment by urain39** [comment]
可能是命名空间冲突？好像有两个active类，意义不同但是名字相同

**Comment by urain39** [comment]
跟踪代码：index.html 345行 active类

**Comment by urain39** [comment]
在完成的任务数大于5个时好像会出现，有待观察。

**Comment by uzilla** [comment]
fallback到原来的样式了，暂时不管这个问题了
